### ISSUE TITLE
want to join you

### ISSUE THREAD

**Issue by taiojia** [vektra/tachyon#16]
I like tachyon!! I am a golang developer, can I join your organization?

**Comment by evanphx** [comment]
What do you want to do?

**Comment by taiojia** [comment]
how can I join the team?

**Comment by skottler** [comment]
Generally the best way to get involved is submit pull requests for relevant features, bugs, or other improvements. Over time that may lead to getting added to the team. It's ideal to start using tachyon and submit changes as you see fit.
