### ISSUE TITLE
Use `otto`, the JS interpreter instead of LISP!

### ISSUE THREAD

**Issue by abourget** [vektra/tachyon#17]
Just because there's a larger public with `js` knowledge :)

**Comment by evanphx** [comment]
Use otto instead of tachyon?

**Comment by abourget** [comment]
No :-) as the embedded interpreter

Le mer. 6 janv. 2016 15:09, Evan Phoenix notifications@github.com a
écrit :

**Comment by evanphx** [comment]
Ah ah! That otto! Yes, I agree.
